# Generated by Django 5.2 on 2025-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Visit'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
    ]
