# Generated by Django 5.2 on 2025-04-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_package_description_remove_package_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.booking'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
