# Generated by Django 5.2 on 2025-04-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_testimonial_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.booking'),
        ),
    ]
