# Generated by Django 5.2 on 2025-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_gallery_description_alter_testimonial_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
